// app/layout.js (or pages/_app.js)
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import logo from '../../public/logo.png'
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AgentFlow-Multi-Agent Orchestration Platform",
  description: "Generated by create next app",
  icons: {
  icon: '/logo.png',            // Your favicon path
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
